### ISSUE TITLE
USER STORY: Community Page

### ISSUE THREAD

**Issue by EddieCodeHub** [EddieCodeHub/My-First-Agile-Project#7]
As a **user** I can **Add my own posts to a community page, and be able to look at community posts from specified walks** so that **There is more of a sense of community within the site/club**

## Acceptance Criteria:

- I should be able to post about events I have been on.
- I should be able to add pictures and comments to aid community interaction.
- Only members of the club should be able to post. This is to be able to control "Troll" behaviour.

## Tasks:

- [ ] Change the Gallery into a "Community Posts" page.
- [ ] Add ability to post Pictures/comments to page (like a forum).
- [ ] Check whether somebody is a member before allowing to post.
