### ISSUE TITLE
USER STORY: Functional Membership

### ISSUE THREAD

**Issue by EddieCodeHub** [EddieCodeHub/My-First-Agile-Project#8]
As a **member** I can **access more interactive content on the page** so that **I can feel like a member of the community**

## Acceptance Criteria:

- Make Community Page run membership checks before being able to post.
- Ability to "book" myself onto runs. This will allow for better planning for the amount of people.
- Ability to carry on as a guest if i'm not interested in signing up. 
- Email verification to prevent fraudulent behaviour.

## Tasks:

- [ ] Create membership check on Community page.
- [ ] Create ability to book onto runs with membership check.
- [ ] verification email sent after account setup.
